#!/usr/bin/env python3
"""
generate-css.py — write the ready-to-use CSS for a built quanta-strike family.

The whole point of quanta-strike is that a strike is only pixel-perfect at its own
size: quanta-strike-16 at 16px, quanta-strike-12 at 12px. Size and family are a
PAIR. This script emits CSS that binds them together so a user can't hold it wrong:
each strike gets a class that sets font-family AND font-size at once.

It reads a built WOFF2 tree (the one convert-woff2.py produces):

    <woff2-dir>/quanta-strike/quanta-strike-16-regular.woff2        proportional
    <woff2-dir>/quanta-strike-mono/quanta-strike-16-mono-regular.woff2   mono

...derives the strike size N from each filename, and writes:

    quanta-strike.css       every strike, both variants
    quanta-strike-16.css    one strike, both variants (for per-strike imports)

Each file holds @font-face blocks, --font-strike-N custom properties, and the
paired utility classes:

    .qs-16      { font-family: "quanta-strike-16";      font-size: 16px; }
    .qs-16-mono { font-family: "quanta-strike-16-mono"; font-size: 16px; }

line-height is 1 so a line box is a whole number of pixels, which keeps leading on
the grid too. Override it per project if you want more air.

URLs default to the variant-folder layout above, relative to the output dir. Use
--flat when every woff2 sits in one folder, and --url-prefix to point at wherever
the fonts are served from.

Usage:
    generate-css.py <woff2-dir> [--out DIR] [--url-prefix P] [--flat]

    generate-css.py build/woff2
    generate-css.py build/woff2 --out package/css --flat --url-prefix ../fonts/
"""

import argparse
import re
import sys
from pathlib import Path

# quanta-strike-16-regular.woff2 / quanta-strike-16-mono-regular.woff2
FILENAME_RE = re.compile(r"^quanta-strike-(\d+)(-mono)?-regular\.woff2$")

PROP_GROUP = "quanta-strike"
MONO_GROUP = "quanta-strike-mono"

HEADER = """/* quanta-strike — generated by generate-css.py. Do not edit by hand.
 *
 * Each strike is its own family, drawn for one size. It is pixel-perfect at that
 * size and blurry at any other, so the classes below set family and size together.
 * Use them as a pair and never pull the size out on its own.
 *
 *   <p class="qs-16">body text</p>
 *   <code class="qs-12-mono">code</code>
 *
 * https://github.com/dithernaut/quanta-strike
 */
"""


def find_strikes(woff2_dir):
    """Map strike size -> {'prop': relpath, 'mono': relpath} for what's on disk."""
    strikes = {}
    for group, variant in ((PROP_GROUP, "prop"), (MONO_GROUP, "mono")):
        group_dir = woff2_dir / group
        if not group_dir.is_dir():
            continue
        for path in sorted(group_dir.glob("*.woff2")):
            match = FILENAME_RE.match(path.name)
            if not match:
                continue
            size = int(match.group(1))
            is_mono = match.group(2) is not None
            # A mono file must live in the mono group, and vice versa.
            if is_mono != (variant == "mono"):
                continue
            strikes.setdefault(size, {})[variant] = f"{group}/{path.name}"
    return dict(sorted(strikes.items()))


def url_for(relpath, url_prefix, flat):
    name = Path(relpath).name if flat else relpath
    return f"{url_prefix}{name}"


def face(family, url):
    return (
        "@font-face {\n"
        f'  font-family: "{family}";\n'
        f'  src: url("{url}") format("woff2");\n'
        "  font-weight: normal;\n"
        "  font-style: normal;\n"
        "  font-display: block;\n"
        "}\n"
    )


def render_core(strikes, sizes, url_prefix, flat):
    """The unopinionated layer: @font-face, the vars, and the mono swap.

    No utility classes here. A project with its own type scale wants exactly this
    and nothing more.
    """
    out = [HEADER]

    for size in sizes:
        files = strikes[size]
        if "prop" in files:
            out.append(face(f"quanta-strike-{size}", url_for(files["prop"], url_prefix, flat)))
        if "mono" in files:
            out.append(face(f"quanta-strike-{size}-mono", url_for(files["mono"], url_prefix, flat)))

    # Custom properties, so a project can wire strikes into its own type scale.
    out.append("\n:root {\n")
    for size in sizes:
        files = strikes[size]
        if "prop" in files:
            out.append(f'  --font-strike-{size}: "quanta-strike-{size}";\n')
        if "mono" in files:
            out.append(f'  --font-strike-{size}-mono: "quanta-strike-{size}-mono";\n')
    out.append("}\n")

    # Redefining the vars on a subtree switches every strike under it to mono
    # without touching a single font-size. Sizes stay put, the design swaps.
    out.append(
        "\n/* Switch a subtree to the mono variant. Sizes stay exactly as they are. */\n"
        ".qs-mono {\n"
    )
    for size in sizes:
        if "mono" in strikes[size]:
            out.append(f'  --font-strike-{size}: "quanta-strike-{size}-mono";\n')
    out.append("}\n")

    return "".join(out)


def render_utilities(strikes, sizes, core_import):
    """The opinionated layer: one class per strike, family and size bound together.

    Sizes are in px on purpose. This is the locked mode, so a strike renders at
    exactly 1 CSS px per source pixel no matter what the root font-size does.
    Projects that want the uniform zoom knob use the vars and their own rem scale
    instead.
    """
    out = []
    if core_import:
        out.append(f'@import "{core_import}";\n\n')
        out.append(HEADER)
    out.append("\n/* Family and size together. Never split them. */\n")
    for size in sizes:
        files = strikes[size]
        if "prop" in files:
            out.append(
                f".qs-{size} {{ font-family: var(--font-strike-{size}); "
                f"font-size: {size}px; line-height: 1; }}\n"
            )
        if "mono" in files:
            out.append(
                f".qs-{size}-mono {{ font-family: var(--font-strike-{size}-mono); "
                f"font-size: {size}px; line-height: 1; }}\n"
            )
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(description="Generate quanta-strike CSS from a built WOFF2 tree.")
    parser.add_argument("woff2_dir", help="directory holding quanta-strike/ and quanta-strike-mono/")
    parser.add_argument("--out", help="where to write the CSS (default: the woff2 dir)")
    parser.add_argument("--url-prefix", default="", help="prepended to every font URL")
    parser.add_argument("--flat", action="store_true", help="every woff2 sits in one folder")
    args = parser.parse_args()

    woff2_dir = Path(args.woff2_dir)
    if not woff2_dir.is_dir():
        print(f"error: {woff2_dir} is not a directory", file=sys.stderr)
        return 1

    strikes = find_strikes(woff2_dir)
    if not strikes:
        print(f"error: no quanta-strike woff2 files found under {woff2_dir}", file=sys.stderr)
        return 1

    out_dir = Path(args.out) if args.out else woff2_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    sizes = list(strikes)
    written = []

    combined = out_dir / "quanta-strike.css"
    combined.write_text(render_core(strikes, sizes, args.url_prefix, args.flat))
    written.append(combined)

    utilities = out_dir / "quanta-strike-utilities.css"
    utilities.write_text(render_utilities(strikes, sizes, "./quanta-strike.css"))
    written.append(utilities)

    # A per-strike file is the "I only need one size" path, so it carries its own
    # utility classes. No second import to remember.
    for size in sizes:
        path = out_dir / f"quanta-strike-{size}.css"
        path.write_text(
            render_core(strikes, [size], args.url_prefix, args.flat)
            + render_utilities(strikes, [size], None)
        )
        written.append(path)

    variants = sum(len(v) for v in strikes.values())
    print(f"Wrote {len(written)} CSS file(s) for {len(sizes)} strike(s), {variants} font file(s):")
    for path in written:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
