#!/usr/bin/env python3
"""
generate-css.py — write the ready-to-use CSS for a built quanta-strike family.

The whole point of quanta-strike is that a strike is only pixel-perfect at its own
size: quanta-strike-16 at 16px, quanta-strike-12 at 12px. Size and family are a
PAIR. This script emits CSS that binds them together so a user can't hold it wrong:
each strike gets a class that sets font-family AND font-size at once.

It reads a built WOFF2 tree (the one scripts/convert-woff2.py produces):

    <woff2-dir>/quanta-strike/quanta-strike-16-regular.woff2        proportional
    <woff2-dir>/quanta-strike-mono/quanta-strike-16-mono-regular.woff2   mono

...derives the strike size N from each filename, and writes:

    quanta-strike.css            every strike, both variants
    quanta-strike-mono.css       every strike, mono only (no proportional faces)
    quanta-strike-16.css         one strike, both variants
    quanta-strike-16-mono.css    one strike, mono only
    scale/base-N.css             Tailwind type-scale (proportional via --font-strike-N)
    scale/base-N-mono.css        same ladder, mono via --font-strike-N-mono
    grid.css                     Tailwind spacing grid (--spacing = one source pixel)

Each file holds @font-face blocks, --font-strike-N custom properties, and the
paired utility classes:

    .qs-16      { font-family: "quanta-strike-16";      font-size: 16px; }
    .qs-16-mono { font-family: "quanta-strike-16-mono"; font-size: 16px; }

The mono-only entry points exist so a code/TUI project can import mono without
pulling proportional faces. In those files --font-strike-N also points at mono,
so existing .qs-N / scale consumers keep working.

line-height is 1 so a line box is a whole number of pixels, which keeps leading on
the grid too. Override it per project if you want more air.

The scale presets are opt-in Tailwind @theme files. Rem sizes are always N/16 so
html { font-size: 100% } keeps 1 source pixel = 1 CSS px; picking base-12 only
moves which strike is text-base, it does not change the rem math. See
scale_map() for how neighbors fill the ladder.

URLs default to the variant-folder layout above, relative to the output dir. Use
--flat when every woff2 sits in one folder, and --url-prefix to point at wherever
the fonts are served from.

Usage:
    scripts/generate-css.py <woff2-dir> [--out DIR] [--url-prefix P] [--flat]

    scripts/generate-css.py build/woff2
    scripts/generate-css.py build/woff2 --out package/css --flat --url-prefix ../fonts/
"""

import argparse
import re
import sys
from fractions import Fraction
from pathlib import Path

# quanta-strike-16-regular.woff2 / quanta-strike-16-mono-regular.woff2
FILENAME_RE = re.compile(r"^quanta-strike-(\d+)(-mono)?-regular\.woff2$")

PROP_GROUP = "quanta-strike"
MONO_GROUP = "quanta-strike-mono"

# Rem root for the type scale. Browser default 1rem = 16px, so strike N is
# always N/16 rem. Choosing a different "base" strike only remaps semantic
# steps — it does not change this divisor (that would break the zoom story).
REM_ROOT = 16

# Tailwind steps outward from base. Nearest-to-base first.
SCALE_BELOW = ("sm", "xs", "2xs", "3xs", "4xs")
SCALE_ABOVE = ("lg", "xl", "2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl")

# Full ladder order, used to alias leftover larger steps onto the biggest strike
# (same trick the site uses: text-5xl+ → strike 32 when 4xl already is 32).
SCALE_STEP_ORDER = ("4xs", "3xs", "2xs", "xs", "sm", "base", "lg", "xl",
                    "2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl")

HEADER = """/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.
 *
 * Each strike is its own family, drawn for one size. It is pixel-perfect at that
 * size and blurry at any other, so the classes below set family and size together.
 * Use them as a pair and never pull the size out on its own.
 *
 *   <p class="qs-16">body text</p>
 *   <code class="qs-12-mono">code</code>
 *
 * https://github.com/dithernaut/quanta-strike
 */
"""


def find_strikes(woff2_dir):
    """Map strike size -> {'prop': relpath, 'mono': relpath} for what's on disk."""
    strikes = {}
    for group, variant in ((PROP_GROUP, "prop"), (MONO_GROUP, "mono")):
        group_dir = woff2_dir / group
        if not group_dir.is_dir():
            continue
        for path in sorted(group_dir.glob("*.woff2")):
            match = FILENAME_RE.match(path.name)
            if not match:
                continue
            size = int(match.group(1))
            is_mono = match.group(2) is not None
            # A mono file must live in the mono group, and vice versa.
            if is_mono != (variant == "mono"):
                continue
            strikes.setdefault(size, {})[variant] = f"{group}/{path.name}"
    return dict(sorted(strikes.items()))


def url_for(relpath, url_prefix, flat):
    name = Path(relpath).name if flat else relpath
    return f"{url_prefix}{name}"


def face(family, url):
    return (
        "@font-face {\n"
        f'  font-family: "{family}";\n'
        f'  src: url("{url}") format("woff2");\n'
        "  font-weight: normal;\n"
        "  font-style: normal;\n"
        "  font-display: block;\n"
        "}\n"
    )


def render_core(strikes, sizes, url_prefix, flat, *, mono_only=False):
    """The unopinionated layer: @font-face, the vars, and (when both) the mono swap.

    No utility classes here. A project with its own type scale wants exactly this
    and nothing more.

    mono_only=True emits only mono faces. --font-strike-N points at mono too, so
    consumers that already bind on the un-suffixed var get mono without rewriting.
    """
    out = [HEADER]

    for size in sizes:
        files = strikes[size]
        if not mono_only and "prop" in files:
            out.append(face(f"quanta-strike-{size}", url_for(files["prop"], url_prefix, flat)))
        if "mono" in files:
            out.append(face(f"quanta-strike-{size}-mono", url_for(files["mono"], url_prefix, flat)))

    # Custom properties, so a project can wire strikes into its own type scale.
    out.append("\n:root {\n")
    for size in sizes:
        files = strikes[size]
        if mono_only:
            if "mono" in files:
                # Primary var → mono so .qs-N / scale/base-N.css keep working.
                out.append(f'  --font-strike-{size}: "quanta-strike-{size}-mono";\n')
                out.append(f'  --font-strike-{size}-mono: "quanta-strike-{size}-mono";\n')
        else:
            if "prop" in files:
                out.append(f'  --font-strike-{size}: "quanta-strike-{size}";\n')
            if "mono" in files:
                out.append(f'  --font-strike-{size}-mono: "quanta-strike-{size}-mono";\n')
    out.append("}\n")

    # Combined core only: redefine the vars on a subtree to swap design, not size.
    # Mono-only core is already mono — the class would be a no-op.
    if not mono_only:
        out.append(
            "\n/* Switch a subtree to the mono variant. Sizes stay exactly as they are. */\n"
            ".qs-mono {\n"
        )
        for size in sizes:
            if "mono" in strikes[size]:
                out.append(f'  --font-strike-{size}: "quanta-strike-{size}-mono";\n')
        out.append("}\n")

    return "".join(out)


def render_utilities(strikes, sizes, core_import, *, mono_only=False):
    """The opinionated layer: one class per strike, family and size bound together.

    Sizes are in px on purpose. This is the locked mode, so a strike renders at
    exactly 1 CSS px per source pixel no matter what the root font-size does.
    Projects that want the uniform zoom knob use the vars and their own rem scale
    instead.

    mono_only=True only emits classes for strikes that have a mono face. .qs-N
    still works because the mono core points --font-strike-N at mono.
    """
    out = []
    if core_import:
        out.append(f'@import "{core_import}";\n\n')
        out.append(HEADER)
    out.append("\n/* Family and size together. Never split them. */\n")
    for size in sizes:
        files = strikes[size]
        if mono_only:
            if "mono" not in files:
                continue
            out.append(
                f".qs-{size} {{ font-family: var(--font-strike-{size}); "
                f"font-size: {size}px; line-height: 1; }}\n"
            )
            out.append(
                f".qs-{size}-mono {{ font-family: var(--font-strike-{size}-mono); "
                f"font-size: {size}px; line-height: 1; }}\n"
            )
        else:
            if "prop" in files:
                out.append(
                    f".qs-{size} {{ font-family: var(--font-strike-{size}); "
                    f"font-size: {size}px; line-height: 1; }}\n"
                )
            if "mono" in files:
                out.append(
                    f".qs-{size}-mono {{ font-family: var(--font-strike-{size}-mono); "
                    f"font-size: {size}px; line-height: 1; }}\n"
                )
    return "".join(out)


def rem_size(strike):
    """CSS rem literal for a strike: always strike/16 (see REM_ROOT)."""
    value = Fraction(strike, REM_ROOT)
    if value.denominator == 1:
        return f"{value.numerator}rem"
    # Prefer a short decimal when it terminates cleanly (0.75, 1.125, …).
    decimal = float(value)
    as_str = f"{decimal:.10f}".rstrip("0").rstrip(".")
    return f"{as_str}rem"


def scale_map(base, strikes):
    """Map Tailwind text steps → strike sizes with `base` as text-base.

    Strikes below the base fill sm, xs, 2xs… (nearest first). Strikes above fill
    lg, xl, 2xl…. Any leftover larger Tailwind steps alias onto the biggest
    strike so an unbound text-5xl cannot silently drop the family pairing.
    """
    if base not in strikes:
        raise ValueError(f"base strike {base} is not in the strike list")

    below = sorted((s for s in strikes if s < base), reverse=True)
    above = sorted(s for s in strikes if s > base)

    mapping = {"base": base}
    for step, strike in zip(SCALE_BELOW, below):
        mapping[step] = strike
    for step, strike in zip(SCALE_ABOVE, above):
        mapping[step] = strike

    max_strike = max(strikes)
    # Steps at or above the largest assigned step, still missing → same strike.
    assigned_order = [s for s in SCALE_STEP_ORDER if s in mapping]
    last_step = assigned_order[-1]
    last_idx = SCALE_STEP_ORDER.index(last_step)
    for step in SCALE_STEP_ORDER[last_idx + 1 :]:
        mapping.setdefault(step, max_strike)

    # Stable output: ladder order, not insertion order.
    return [(step, mapping[step]) for step in SCALE_STEP_ORDER if step in mapping]


def render_scale(base, strikes, *, mono=False):
    """Optional Tailwind type-scale preset: @theme sizes + paired text-* utilities.

    Does not import the core CSS — the consumer loads quanta-strike (or
    quanta-strike/mono.css) first so the --font-strike-N vars exist. Does not
    touch html font-size (that's the zoom knob). body gets the base pair so
    unclassed copy stays sharp.

    mono=True binds text-* / body to --font-strike-N-mono, so the scale is mono
    even when the combined core (both variants) is loaded.
    """
    scale = scale_map(base, strikes)
    suffix = "-mono" if mono else ""
    core_import = "quanta-strike/mono.css" if mono else "quanta-strike"
    variant_note = " (mono)" if mono else ""

    def font_var(n):
        return f"--font-strike-{n}-mono" if mono else f"--font-strike-{n}"

    lines = [
        "/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.\n"
        " *\n"
        f" * Type scale with strike {base} as text-base{variant_note}.\n"
        " * Rem sizes are always N/16, so html { font-size: 100% } keeps\n"
        " * 1 source pixel = 1 CSS px. Zoom with html { font-size: …% };\n"
        " * do not change the rem values.\n"
        " *\n"
        " *   @import \"tailwindcss\";\n"
        f" *   @import \"{core_import}\";\n"
        f" *   @import \"quanta-strike/scale/base-{base}{suffix}.css\";\n"
        " *\n"
        " * https://github.com/dithernaut/quanta-strike\n"
        " */\n"
        "\n@theme {\n",
    ]
    for step, strike in scale:
        lines.append(f"  --text-{step}: {rem_size(strike)};\n")
        lines.append(f"  --text-{step}--line-height: 1;\n")
    lines.append("}\n")

    lines.append(
        "\n/* Family and size together. text-* alone would drop the strike. */\n"
        "@layer utilities {\n"
    )
    # Group aliases that share a strike onto one rule where consecutive.
    by_strike = {}
    for step, strike in scale:
        by_strike.setdefault(strike, []).append(step)
    for strike, steps in by_strike.items():
        selectors = ",\n".join(f"  .text-{step}" for step in steps)
        lines.append(
            f"{selectors} {{\n"
            f"    font-family: var({font_var(strike)});\n"
            f"    font-size: var(--text-{steps[0]});\n"
            f"    line-height: 1;\n"
            f"  }}\n"
        )
    lines.append("}\n")

    lines.append(
        "\n@layer base {\n"
        "  body {\n"
        f"    font-family: var({font_var(base)});\n"
        "    font-size: var(--text-base);\n"
        "    line-height: 1;\n"
        "  }\n"
        "}\n"
    )
    return "".join(lines)


# Tailwind's border-width utilities, suffix → the properties they set. The bare
# class (no number) is 1px in stock Tailwind, i.e. one source pixel here.
BORDER_SIDES = (
    ("", ("border-width",)),
    ("-x", ("border-left-width", "border-right-width")),
    ("-y", ("border-top-width", "border-bottom-width")),
    ("-t", ("border-top-width",)),
    ("-r", ("border-right-width",)),
    ("-b", ("border-bottom-width",)),
    ("-l", ("border-left-width",)),
    ("-s", ("border-inline-start-width",)),
    ("-e", ("border-inline-end-width",)),
)

# Tailwind's documented widths. Anything else (border-3, border-5) stays literal
# px — covering every integer would bloat the sheet for no one.
BORDER_WIDTHS = (1, 2, 4, 8)


def grid_length(n):
    """N source pixels as a CSS length. 1 needs no calc()."""
    return "var(--qs-px)" if n == 1 else f"calc(var(--qs-px) * {n})"


def border_grid_rules():
    """Every border-width utility — all sides, axes and logical edges.

    Stock Tailwind writes these as literal px, so they ignore the zoom that the
    strikes and --spacing follow.
    """
    lines = []
    for suffix, props in BORDER_SIDES:
        # Bare class first (.border, .border-l), then the numbered steps.
        for name, n in [(f"border{suffix}", 1)] + [
            (f"border{suffix}-{w}", w) for w in BORDER_WIDTHS
        ]:
            decls = " ".join(f"{p}: {grid_length(n)};" for p in props)
            lines.append(f"  .{name} {{ {decls} }}\n")
    return "".join(lines)


def render_grid():
    """Optional Tailwind pixel grid. Base-independent, no strike data needed.

    Sizes do NOT change. Tailwind's default --spacing (0.25rem) is already
    exactly 4 source pixels, so the stock scale is grid-aligned at every step and
    stays that way under zoom — restating it in --qs-px only makes the grid the
    source of truth, so re-pointing --qs-px moves spacing with it.

    The real off-grid offenders are the px-literal widths (border, outline).
    Those stay literal px while the page zooms, so at font-size: 200% a 1px
    border is half a source pixel. Pinned to --qs-px here. Rings are left alone
    on purpose: v4 builds them from an internal shadow, not a width property.

    --qs-px lives in :root, not @theme, so it survives Tailwind's tree-shaking
    and is available for hand-rolled lengths.
    """
    rem = rem_size(1)  # one source pixel = 1/16rem, same divisor as the scale
    return (
        "/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.\n"
        " *\n"
        " * Optional pixel grid. Spacing keeps Tailwind's default sizes — 0.25rem is\n"
        " * already exactly 4 source pixels, so p-4 is still 16px — and is restated\n"
        " * in source pixels so the grid is the source of truth. What this really\n"
        " * fixes is the px-literal widths (border, outline): they ignore zoom,\n"
        " * so at html { font-size: 200% } a 1px border is half a source pixel.\n"
        " * Base-independent; pairs with any base-N.\n"
        " *\n"
        " *   @import \"tailwindcss\";\n"
        " *   @import \"quanta-strike\";\n"
        " *   @import \"quanta-strike/scale/base-16.css\";\n"
        " *   @import \"quanta-strike/grid.css\";\n"
        " *\n"
        " * https://github.com/dithernaut/quanta-strike\n"
        " */\n"
        "\n:root {\n"
        f"  --qs-px: {rem}; /* one source pixel = 1 CSS px at html {{ font-size: 100% }} */\n"
        "}\n"
        "\n@theme {\n"
        "  /* Same as Tailwind's 0.25rem default. Sizes are unchanged; the step is\n"
        "     just expressed as 4 source pixels so it follows --qs-px. */\n"
        "  --spacing: calc(var(--qs-px) * 4);\n"
        "}\n"
        "\n/* px-literal widths: the only part of stock Tailwind that leaves the grid\n"
        "   when the page zooms. One source pixel is the thinnest honest line.\n"
        "   N means N source pixels; other numbers stay literal px — use\n"
        "   border-[length:calc(var(--qs-px)*3)] or var(--qs-px) by hand. */\n"
        "@layer utilities {\n"
        + border_grid_rules()
        + "  .outline { outline-width: var(--qs-px); }\n"
        "}\n"
    )


def main():
    parser = argparse.ArgumentParser(description="Generate quanta-strike CSS from a built WOFF2 tree.")
    parser.add_argument("woff2_dir", help="directory holding quanta-strike/ and quanta-strike-mono/")
    parser.add_argument("--out", help="where to write the CSS (default: the woff2 dir)")
    parser.add_argument("--url-prefix", default="", help="prepended to every font URL")
    parser.add_argument("--flat", action="store_true", help="every woff2 sits in one folder")
    args = parser.parse_args()

    woff2_dir = Path(args.woff2_dir)
    if not woff2_dir.is_dir():
        print(f"error: {woff2_dir} is not a directory", file=sys.stderr)
        return 1

    strikes = find_strikes(woff2_dir)
    if not strikes:
        print(f"error: no quanta-strike woff2 files found under {woff2_dir}", file=sys.stderr)
        return 1

    out_dir = Path(args.out) if args.out else woff2_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    sizes = list(strikes)
    mono_sizes = [s for s in sizes if "mono" in strikes[s]]
    written = []

    combined = out_dir / "quanta-strike.css"
    combined.write_text(render_core(strikes, sizes, args.url_prefix, args.flat))
    written.append(combined)

    if mono_sizes:
        mono_core = out_dir / "quanta-strike-mono.css"
        mono_core.write_text(
            render_core(strikes, mono_sizes, args.url_prefix, args.flat, mono_only=True)
        )
        written.append(mono_core)

    utilities = out_dir / "quanta-strike-utilities.css"
    utilities.write_text(render_utilities(strikes, sizes, "./quanta-strike.css"))
    written.append(utilities)

    if mono_sizes:
        utilities_mono = out_dir / "quanta-strike-utilities-mono.css"
        utilities_mono.write_text(
            render_utilities(
                strikes, mono_sizes, "./quanta-strike-mono.css", mono_only=True
            )
        )
        written.append(utilities_mono)

    # A per-strike file is the "I only need one size" path, so it carries its own
    # utility classes. No second import to remember.
    for size in sizes:
        path = out_dir / f"quanta-strike-{size}.css"
        path.write_text(
            render_core(strikes, [size], args.url_prefix, args.flat)
            + render_utilities(strikes, [size], None)
        )
        written.append(path)

    for size in mono_sizes:
        path = out_dir / f"quanta-strike-{size}-mono.css"
        path.write_text(
            render_core(strikes, [size], args.url_prefix, args.flat, mono_only=True)
            + render_utilities(strikes, [size], None, mono_only=True)
        )
        written.append(path)

    # One type-scale preset per strike (prop + mono). Opt-in; core stays unopinionated.
    scale_dir = out_dir / "scale"
    if scale_dir.exists():
        for old in scale_dir.glob("base-*.css"):
            old.unlink()
    scale_dir.mkdir(parents=True, exist_ok=True)
    for size in sizes:
        path = scale_dir / f"base-{size}.css"
        path.write_text(render_scale(size, sizes))
        written.append(path)
    for size in mono_sizes:
        path = scale_dir / f"base-{size}-mono.css"
        path.write_text(render_scale(size, sizes, mono=True))
        written.append(path)

    # Base-independent spacing grid. Opt-in, same tier as the scale presets.
    grid = out_dir / "grid.css"
    grid.write_text(render_grid())
    written.append(grid)

    variants = sum(len(v) for v in strikes.values())
    print(f"Wrote {len(written)} CSS file(s) for {len(sizes)} strike(s), {variants} font file(s):")
    for path in written:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())

