#!/usr/bin/env python3
"""
generate-css.py — write the ready-to-use CSS for a built quanta-strike family.

The whole point of quanta-strike is that a strike is only pixel-perfect at its own
size: quanta-strike-16 at 16px, quanta-strike-12 at 12px. Size and family are a
PAIR. This script emits CSS that binds them together so a user can't hold it wrong:
each strike gets a class that sets font-family AND font-size at once.

It reads a built WOFF2 tree (the one scripts/convert-woff2.py produces):

    <woff2-dir>/quanta-strike/quanta-strike-16-regular.woff2        proportional
    <woff2-dir>/quanta-strike-mono/quanta-strike-16-mono-regular.woff2   mono

...derives the strike size N and the weight from each filename. Every weight a
strike ships (regular, bold, light, ...) becomes another @font-face on the SAME
family, so font-weight selects it and the classes below never change:

    <p class="qs-16">body <strong>bold</strong> body</p>

It writes:

    fonts.css                @font-face + --font-strike-N vars (no classes)
    quanta-strike.css        fonts.css + locked .qs-N classes (px, ignore zoom)
    utilities.css            alias of quanta-strike.css
    mono.css                 mono faces + vars only
    utilities-mono.css       mono.css + locked .qs-N / .qs-N-mono classes
    N.css / N-mono.css       one strike (faces + locked classes)
    base-N.css               Tailwind preset: fonts + grid + zoom + theme
    base-N-mono.css          same, mono faces
    scale/base-N.css         @import alias of ../base-N.css
    grid.css                 --qs-px + spacing/radius/tracking + border/ring snaps

--qs-px is the system unit (one source pixel). --qs-zoom is the user dial.
grid.css owns --qs-px; base-N owns --qs-zoom. Every theme length is
calc(var(--qs-px) * N). See docs/CSS-API-PLAN.md.

Locked .qs-N classes stay in px and do NOT follow --qs-zoom — they are the
manual/plain-CSS path. On a base-N page, use text-* instead.

URLs default to the variant-folder layout above, relative to the output dir. Use
--flat when every woff2 sits in one folder, and --url-prefix to point at wherever
the fonts are served from.

Usage:
    scripts/generate-css.py <woff2-dir> [--out DIR] [--url-prefix P] [--flat]

    scripts/generate-css.py build/woff2
    scripts/generate-css.py build/woff2 --out package --flat --url-prefix fonts/
"""

import argparse
import re
import struct
import sys
from fractions import Fraction
from pathlib import Path

# quanta-strike-16-regular.woff2 / quanta-strike-16-mono-bold.woff2
FILENAME_RE = re.compile(r"^quanta-strike-(\d+)(-mono)?-([a-z]+)\.woff2$")

# Style token in the filename -> CSS font-weight. Mirrors WEIGHT_MAP in
# scripts/font-metadata-patcher.py, which is what stamps OS/2 on the font
# itself; keep the two in step or CSS and the font will disagree about a weight.
CSS_WEIGHTS = {
    "thin": 100,
    "hairline": 100,
    "extralight": 200,
    "ultralight": 200,
    "light": 300,
    "regular": 400,
    "normal": 400,
    "book": 400,
    "medium": 500,
    "semibold": 600,
    "demibold": 600,
    "bold": 700,
    "extrabold": 800,
    "ultrabold": 800,
    "black": 900,
    "heavy": 900,
}

PROP_GROUP = "quanta-strike"
MONO_GROUP = "quanta-strike-mono"

# Rem root for the type scale. Browser default 1rem = 16px, so one source pixel
# is 1/16rem at --qs-zoom: 1. Zoom multiplies --qs-px; it does not change this.
REM_ROOT = 16

# Tailwind steps outward from base. Nearest-to-base first.
SCALE_BELOW = ("sm", "xs", "2xs", "3xs", "4xs")
SCALE_ABOVE = ("lg", "xl", "2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl")

# Full ladder order, used to alias leftover larger steps onto the biggest strike
# (same trick the site uses: text-5xl+ → strike 32 when 4xl already is 32).
SCALE_STEP_ORDER = ("4xs", "3xs", "2xs", "xs", "sm", "base", "lg", "xl",
                    "2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl")

# Radius steps → source-pixel multiples. Matches Tailwind's rem defaults at
# zoom 1 (0.125rem = 2px, …) so rounded-* sizes are unchanged until zoom moves.
RADIUS_STEPS = (
    ("xs", 2),
    ("sm", 4),
    ("md", 6),
    ("lg", 8),
    ("xl", 12),
    ("2xl", 16),
    ("3xl", 24),
    ("4xl", 32),
)

# Tracking: stock values are em fractions and push glyph origins off the grid.
# Integer units (or 0) only.
TRACKING_STEPS = (
    ("tighter", -1),
    ("tight", 0),
    ("normal", 0),
    ("wide", 1),
    ("wider", 2),
    ("widest", 4),
)

HEADER = """/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.
 *
 * Each strike is its own family, drawn for one size. It is pixel-perfect at that
 * size and blurry at any other, so the classes below set family and size together.
 * Use them as a pair and never pull the size out on its own.
 *
 *   <p class="qs-16">body text</p>
 *   <code class="qs-12-mono">code</code>
 *
 * https://github.com/dithernaut/quanta-strike
 */
"""


def parse_style_token(token):
    """'bolditalic' -> (700, True). None weight if it isn't a style we know.

    The token is whatever the patcher put after the family in the filename: the
    style with its spaces stripped, lowercased ('regular', 'bold', 'semibold',
    'bolditalic').
    """
    italic = False
    for suffix in ("italic", "oblique"):
        if token.endswith(suffix):
            token = token[: -len(suffix)]
            italic = True
            break
    return CSS_WEIGHTS.get(token or "regular"), italic


def find_strikes(woff2_dir):
    """Map strike size -> {'prop': [face...], 'mono': [face...]} for what's on disk.

    A face is (weight, italic, relpath). Every weight of a strike is a face on
    the SAME CSS family, so `font-weight: bold` picks the bold file and nothing
    downstream has to know which weights exist.
    """
    strikes = {}
    for group, variant in ((PROP_GROUP, "prop"), (MONO_GROUP, "mono")):
        group_dir = woff2_dir / group
        if not group_dir.is_dir():
            continue
        for path in sorted(group_dir.glob("*.woff2")):
            match = FILENAME_RE.match(path.name)
            if not match:
                continue
            size = int(match.group(1))
            is_mono = match.group(2) is not None
            # A mono file must live in the mono group, and vice versa.
            if is_mono != (variant == "mono"):
                continue
            weight, italic = parse_style_token(match.group(3))
            if weight is None:
                print(f"warning: skipping {path.name} — unknown style "
                      f"'{match.group(3)}'", file=sys.stderr)
                continue
            strikes.setdefault(size, {}).setdefault(variant, []).append(
                (weight, italic, f"{group}/{path.name}"))

    # Lightest first, upright before italic — stable output, readable diffs.
    for files in strikes.values():
        for faces in files.values():
            faces.sort()
    return dict(sorted(strikes.items()))


def url_for(relpath, url_prefix, flat):
    name = Path(relpath).name if flat else relpath
    return f"{url_prefix}{name}"


def face(family, url, weight=400, italic=False):
    return (
        "@font-face {\n"
        f'  font-family: "{family}";\n'
        f'  src: url("{url}") format("woff2");\n'
        f"  font-weight: {weight};\n"
        f'  font-style: {"italic" if italic else "normal"};\n'
        "  font-display: block;\n"
        "}\n"
    )


def faces(family, entries, url_prefix, flat):
    """One @font-face per weight, all on the same family name.

    That shared name is the whole point: <strong> and font-weight: 700 resolve to
    the bold file on their own, and a strike that ships regular only still gets a
    synthesised bold from the browser exactly as before.
    """
    return [
        face(family, url_for(relpath, url_prefix, flat), weight, italic)
        for weight, italic, relpath in entries
    ]


def render_core(strikes, sizes, url_prefix, flat, *, mono_only=False):
    """Faces + vars only. No utility classes, no --qs-rule.

    fonts.css / mono.css are this layer. A project with its own type scale wants
    exactly this and nothing more.

    mono_only=True emits only mono faces. --font-strike-N points at mono too, so
    consumers that already bind on the un-suffixed var get mono without rewriting.
    """
    out = [HEADER]

    for size in sizes:
        files = strikes[size]
        if not mono_only and "prop" in files:
            out.extend(faces(f"quanta-strike-{size}", files["prop"], url_prefix, flat))
        if "mono" in files:
            out.extend(faces(f"quanta-strike-{size}-mono", files["mono"], url_prefix, flat))

    # Custom properties, so a project can wire strikes into its own type scale.
    out.append("\n:root {\n")
    for size in sizes:
        files = strikes[size]
        if mono_only:
            if "mono" in files:
                # Primary var → mono so .qs-N / base-N keep working.
                out.append(f'  --font-strike-{size}: "quanta-strike-{size}-mono";\n')
                out.append(f'  --font-strike-{size}-mono: "quanta-strike-{size}-mono";\n')
        else:
            if "prop" in files:
                out.append(f'  --font-strike-{size}: "quanta-strike-{size}";\n')
            if "mono" in files:
                out.append(f'  --font-strike-{size}-mono: "quanta-strike-{size}-mono";\n')
    out.append("}\n")

    # Combined core only: redefine the vars on a subtree to swap design, not size.
    # Mono-only core is already mono — the class would be a no-op.
    if not mono_only:
        out.append(
            "\n/* Switch a subtree to the mono variant. Sizes stay exactly as they are. */\n"
            ".qs-mono {\n"
        )
        for size in sizes:
            if "mono" in strikes[size]:
                out.append(f'  --font-strike-{size}: "quanta-strike-{size}-mono";\n')
        out.append("}\n")

    return "".join(out)


# strike -> (stroke px, underline offset px), read from the built TTFs by
# load_decoration(). The fonts are the source of truth: anchor-em.py works the
# numbers out from each strike's own descender depth, which is art, not
# arithmetic, so there is nothing here to re-derive them from.
DECORATION = {}


def read_decoration(ttf, strike):
    """(stroke, underline offset) in px at the strike's native size.

    Straight out of post: underlineThickness, and underlinePosition as the TOP
    of the stroke (negative below the baseline, so the offset is its negation).
    Scaling by strike/upem rather than assuming 128 units per pixel keeps this
    honest for a --scale build, where the em shrinks but the outlines don't.
    """
    data = ttf.read_bytes()
    offsets = {}
    for i in range(struct.unpack(">H", data[4:6])[0]):
        entry = 12 + 16 * i
        tag = data[entry:entry + 4].decode("latin1")
        offsets[tag] = struct.unpack(">I", data[entry + 8:entry + 12])[0]
    head, post = offsets["head"], offsets["post"]
    upem = struct.unpack(">H", data[head + 18:head + 20])[0]
    position, thickness = struct.unpack(">hh", data[post + 8:post + 12])
    return thickness * strike / upem, -position * strike / upem


def load_decoration(ttf_dir, sizes):
    """Fill DECORATION from a built TTF tree; silent no-op when it isn't there.

    Only the proportional face is read: anchor-em.py gives every variant of a
    strike the same metrics, so mono would answer identically.
    """
    if not ttf_dir or not ttf_dir.is_dir():
        return
    for size in sizes:
        matches = sorted(ttf_dir.glob(f"**/quanta-strike-{size}-regular.ttf"))
        if matches:
            DECORATION[size] = read_decoration(matches[0], size)


def decoration_for(strike):
    """The stroke and underline offset a strike's CSS should state.

    Falls back to the build's own rule when the TTFs aren't reachable — enough
    for a standalone run against a bare woff2 folder, though a strike whose
    descender can't hold the full gap (the 6) needs the real font to say so.
    """
    if strike in DECORATION:
        return DECORATION[strike]
    stroke = max(1, (strike + 8) // 16)
    return float(stroke), float(stroke)


def css_px(value):
    """A px length, kept whole when the value is."""
    value = round(value, 3)
    return f"{int(value)}px" if value == int(value) else f"{value}px"


def rem_size(strike):
    """CSS rem literal for a strike: always strike/16 (see REM_ROOT)."""
    value = Fraction(strike, REM_ROOT)
    if value.denominator == 1:
        return f"{value.numerator}rem"
    decimal = float(value)
    as_str = f"{decimal:.10f}".rstrip("0").rstrip(".")
    return f"{as_str}rem"


def grid_length(n):
    """N source pixels as a CSS length. Follows --qs-zoom via --qs-px."""
    if n == 0:
        return "0"
    if n == 1:
        return "var(--qs-px)"
    return f"calc(var(--qs-px) * {n})"


def decoration_lengths(strike):
    """(stroke, offset) as grid lengths for a strike's native metrics."""
    stroke, offset = decoration_for(strike)
    return grid_length(int(round(stroke))), grid_length(int(round(offset)))


def utility_rule(cls, font_var, size):
    """One strike's locked class: family, size and rule metrics bound together.

    Sizes are px on purpose — locked mode ignores --qs-zoom and the root
    font-size. text-underline-offset is the gap from the baseline to the TOP of
    the stroke, the same thing post underlinePosition holds.
    """
    stroke, offset = decoration_for(size)
    return (
        f".{cls} {{ font-family: var(--{font_var}); font-size: {size}px; "
        f"line-height: 1; --qs-rule: {css_px(stroke)}; "
        f"text-decoration-thickness: {css_px(stroke)}; "
        f"text-underline-offset: {css_px(offset)}; }}\n"
    )


def inherit_thickness_rule(classes):
    """Push the stroke down to the elements that actually draw a decoration.

    text-decoration-thickness does NOT inherit (CSS Text Decorations 4), unlike
    text-underline-offset, which does. So an <a>, <u>, <s> or <del> inside a
    strike computes `auto` and the engine picks its own stroke — a hairline in
    WebKit, something else again in Gecko and Blink. Setting it back to inherit
    hands them the strike's whole-pixel value.

    :where() holds the whole selector at zero specificity, so a nested .qs-N
    still wins on its own element and passes its own stroke down from there.
    """
    selector = ", ".join(f".{cls}" for cls in classes)
    return (
        "\n/* text-decoration-thickness does not inherit — hand it to the <a>,\n"
        "   <u>, <s> and <del> that draw the line, or the engine picks its own. */\n"
        f":where({selector}) * {{ text-decoration-thickness: inherit; }}\n"
    )


def render_utilities(strikes, sizes, *, mono_only=False):
    """Locked .qs-N classes: family and size bound together, sizes in px.

    Projects that want the uniform zoom knob use a base-N preset (text-*) instead.
    """
    out = ["\n/* Family and size together. Never split them. */\n"]
    classes = []

    def emit(cls, var, size):
        classes.append(cls)
        out.append(utility_rule(cls, var, size))

    for size in sizes:
        files = strikes[size]
        if mono_only:
            if "mono" not in files:
                continue
            emit(f"qs-{size}", f"font-strike-{size}", size)
            emit(f"qs-{size}-mono", f"font-strike-{size}-mono", size)
        else:
            if "prop" in files:
                emit(f"qs-{size}", f"font-strike-{size}", size)
            if "mono" in files:
                emit(f"qs-{size}-mono", f"font-strike-{size}-mono", size)

    if classes:
        out.append(inherit_thickness_rule(classes))
    return "".join(out)


def scale_map(base, strikes):
    """Map Tailwind text steps → strike sizes with `base` as text-base.

    Strikes below the base fill sm, xs, 2xs… (nearest first). Strikes above fill
    lg, xl, 2xl…. Any leftover larger Tailwind steps alias onto the biggest
    strike so an unbound text-5xl cannot silently drop the family pairing.
    """
    if base not in strikes:
        raise ValueError(f"base strike {base} is not in the strike list")

    below = sorted((s for s in strikes if s < base), reverse=True)
    above = sorted(s for s in strikes if s > base)

    mapping = {"base": base}
    for step, strike in zip(SCALE_BELOW, below):
        mapping[step] = strike
    for step, strike in zip(SCALE_ABOVE, above):
        mapping[step] = strike

    max_strike = max(strikes)
    # Steps at or above the largest assigned step, still missing → same strike.
    assigned_order = [s for s in SCALE_STEP_ORDER if s in mapping]
    last_step = assigned_order[-1]
    last_idx = SCALE_STEP_ORDER.index(last_step)
    for step in SCALE_STEP_ORDER[last_idx + 1 :]:
        mapping.setdefault(step, max_strike)

    # Stable output: ladder order, not insertion order.
    return [(step, mapping[step]) for step in SCALE_STEP_ORDER if step in mapping]


def zoom_default(base):
    """(desktop --qs-zoom, mobile --qs-zoom or None).

    Integers for unconditional defaults (exact on every DPR). base-12 alone ships
    a 1.5 mobile step — retina-only, and the only preset where 1.5 lands useful
    (18px). See docs/CSS-API-PLAN.md § Default zoom per base.
    """
    if base <= 12:
        desktop = 2
    else:
        desktop = 1
    mobile = 1.5 if base == 12 else None
    return desktop, mobile


def render_scale(base, strikes, *, mono=False):
    """Full Tailwind preset: fonts + grid + zoom + theme + paired text-* utilities.

    Imports the fonts entry and grid.css, sets only --qs-zoom (never --qs-px),
    and derives every --text-* from --qs-px. body gets the base pair so unclassed
    copy stays sharp.

    mono=True binds text-* / body to --font-strike-N-mono and imports mono.css.
    """
    scale = scale_map(base, list(strikes))
    suffix = "-mono" if mono else ""
    fonts_file = "mono.css" if mono else "quanta-strike.css"
    import_path = f"quanta-strike/base-{base}{suffix}.css"
    variant_note = " (mono)" if mono else ""
    desktop, mobile = zoom_default(base)

    def font_var(n):
        return f"--font-strike-{n}-mono" if mono else f"--font-strike-{n}"

    lines = [
        "/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.\n"
        " *\n"
        f" * Type scale with strike {base} as text-base{variant_note}.\n"
        " * Every length derives from --qs-px. Zoom with --qs-zoom (this file\n"
        " * sets the default). Setting --qs-zoom yourself replaces every branch,\n"
        " * mobile included.\n"
        " *\n"
        " *   @import \"tailwindcss\";\n"
        f" *   @import \"{import_path}\";\n"
        " *\n"
        " * If you imported a base-N preset, use text-*. Don't use .qs-N — it is\n"
        " * the manual escape hatch and ignores --qs-zoom.\n"
        " *\n"
        " * https://github.com/dithernaut/quanta-strike\n"
        " */\n"
        "\n"
        f'@import "./{fonts_file}";\n'
        '@import "./grid.css";\n'
        "\n"
        "@layer theme {\n"
        f"  :root {{ --qs-zoom: {desktop}; }}\n"
    ]
    if mobile is not None:
        lines.append(
            f"  @media (width < 48rem) {{ :root {{ --qs-zoom: {mobile}; }} }}\n"
        )
    lines.append("}\n")

    lines.append("\n@theme {\n")
    for step, strike in scale:
        lines.append(f"  --text-{step}: {grid_length(strike)};\n")
        lines.append(f"  --text-{step}--line-height: 1;\n")
    lines.append("}\n")

    lines.append(
        "\n/* Family and size together. text-* alone would drop the strike. */\n"
        "@layer utilities {\n"
    )
    by_strike = {}
    for step, strike in scale:
        by_strike.setdefault(strike, []).append(step)
    for strike, steps in by_strike.items():
        selectors = ",\n".join(f"  .text-{step}" for step in steps)
        rule, offset = decoration_lengths(strike)
        lines.append(
            f"{selectors} {{\n"
            f"    font-family: var({font_var(strike)});\n"
            f"    font-size: var(--text-{steps[0]});\n"
            f"    line-height: 1;\n"
            f"    --qs-rule: {rule};\n"
            f"    text-decoration-thickness: {rule};\n"
            f"    text-underline-offset: {offset};\n"
            f"  }}\n"
        )
    text_sel = ", ".join(f".text-{step}" for step, _ in scale)
    lines.append(
        f"  :where({text_sel}) * {{ text-decoration-thickness: inherit; }}\n"
    )
    lines.append("}\n")

    body_rule, body_offset = decoration_lengths(base)
    lines.append(
        "\n@layer base {\n"
        "  body {\n"
        f"    font-family: var({font_var(base)});\n"
        "    font-size: var(--text-base);\n"
        "    line-height: 1;\n"
        f"    --qs-rule: {body_rule};\n"
        f"    text-decoration-thickness: {body_rule};\n"
        f"    text-underline-offset: {body_offset};\n"
        "  }\n"
        "  :where(body) * { text-decoration-thickness: inherit; }\n"
        "}\n"
    )
    return "".join(lines)


def render_scale_alias(base, *, mono=False):
    """Thin re-export so quanta-strike/scale/base-N.css keeps working."""
    suffix = "-mono" if mono else ""
    return (
        "/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.\n"
        " * Alias of ../base-"
        f"{base}{suffix}.css — prefer @import \"quanta-strike/base-{base}{suffix}.css\".\n"
        " */\n"
        f'@import "../base-{base}{suffix}.css";\n'
    )


# Tailwind's documented widths. Anything else (border-3, border-5) stays literal
# px — covering every integer would bloat the sheet for no one.
BORDER_WIDTHS = (1, 2, 4, 8)


def outline_grid_rules():
    lines = ["  .outline { outline-width: var(--qs-px); }\n"]
    for w in BORDER_WIDTHS:
        lines.append(f"  .outline-{w} {{ outline-width: {grid_length(w)}; }}\n")
    return "".join(lines)


def grid_expr(n):
    """N source pixels as a calc()-embeddable expression (no outer calc)."""
    if n == 1:
        return "var(--qs-px)"
    return f"var(--qs-px) * {n}"


def ring_grid_rules():
    """Ring widths are an internal box-shadow — not themeable. Override in place."""
    lines = []
    for name, n in [("ring", 1)] + [(f"ring-{w}", w) for w in BORDER_WIDTHS]:
        expr = grid_expr(n)
        lines.append(
            f"  .{name} {{\n"
            f"    --tw-ring-shadow: var(--tw-ring-inset,) 0 0 0 "
            f"calc({expr} + var(--tw-ring-offset-width)) "
            f"var(--tw-ring-color, currentcolor);\n"
            f"    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), "
            f"var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);\n"
            f"  }}\n"
        )
    for w in BORDER_WIDTHS:
        lines.append(
            f"  .ring-offset-{w} {{\n"
            f"    --tw-ring-offset-width: {grid_length(w)};\n"
            f"    --tw-ring-offset-shadow: var(--tw-ring-inset,) 0 0 0 "
            f"var(--tw-ring-offset-width) var(--tw-ring-offset-color);\n"
            f"  }}\n"
        )
    return "".join(lines)


def divide_grid_rules():
    """divide-x / divide-y set child border widths; not covered by BORDER_SIDES."""
    lines = []
    for axis, (start, end, reverse) in (
        ("x", ("border-inline-start-width", "border-inline-end-width",
               "tw-divide-x-reverse")),
        ("y", ("border-top-width", "border-bottom-width",
               "tw-divide-y-reverse")),
    ):
        for name, n in [(f"divide-{axis}", 1)] + [
            (f"divide-{axis}-{w}", w) for w in BORDER_WIDTHS
        ]:
            expr = grid_expr(n)
            if axis == "x":
                style = (
                    "    border-inline-style: var(--tw-border-style);\n"
                )
            else:
                style = (
                    "    border-bottom-style: var(--tw-border-style);\n"
                    "    border-top-style: var(--tw-border-style);\n"
                )
            lines.append(
                f"  :where(.{name} > :not(:last-child)) {{\n"
                f"    --{reverse}: 0;\n"
                f"{style}"
                f"    {start}: calc(({expr}) * var(--{reverse}));\n"
                f"    {end}: calc(({expr}) * calc(1 - var(--{reverse})));\n"
                f"  }}\n"
            )
    return "".join(lines)


def shadow_theme_rules():
    """Shadow offsets on the grid; blur/spread left soft (no hard edge)."""
    px = "var(--qs-px)"
    p = grid_length  # shorthand
    return (
        f"  --shadow-2xs: 0 {px} rgb(0 0 0 / 0.05);\n"
        f"  --shadow-xs: 0 {px} {p(2)} 0 rgb(0 0 0 / 0.05);\n"
        f"  --shadow-sm: 0 {px} {p(3)} 0 rgb(0 0 0 / 0.1), "
        f"0 {px} {p(2)} {p(-1)} rgb(0 0 0 / 0.1);\n"
        f"  --shadow-md: 0 {p(4)} {p(6)} {p(-1)} rgb(0 0 0 / 0.1), "
        f"0 {p(2)} {p(4)} {p(-2)} rgb(0 0 0 / 0.1);\n"
        f"  --shadow-lg: 0 {p(10)} {p(15)} {p(-3)} rgb(0 0 0 / 0.1), "
        f"0 {p(4)} {p(6)} {p(-4)} rgb(0 0 0 / 0.1);\n"
        f"  --shadow-xl: 0 {p(20)} {p(25)} {p(-5)} rgb(0 0 0 / 0.1), "
        f"0 {p(8)} {p(10)} {p(-6)} rgb(0 0 0 / 0.1);\n"
        f"  --shadow-2xl: 0 {p(25)} {p(50)} {p(-12)} rgb(0 0 0 / 0.25);\n"
        f"  --shadow: 0 {px} {p(3)} 0 rgb(0 0 0 / 0.1), "
        f"0 {px} {p(2)} {p(-1)} rgb(0 0 0 / 0.1);\n"
        f"  --shadow-inner: inset 0 {p(2)} {p(4)} 0 rgb(0 0 0 / 0.05);\n"
        f"  --inset-shadow-2xs: inset 0 {px} rgb(0 0 0 / 0.05);\n"
        f"  --inset-shadow-xs: inset 0 {px} {px} rgb(0 0 0 / 0.05);\n"
        f"  --inset-shadow-sm: inset 0 {p(2)} {p(4)} rgb(0 0 0 / 0.05);\n"
        f"  --drop-shadow-xs: 0 {px} {px} rgb(0 0 0 / 0.05);\n"
        f"  --drop-shadow-sm: 0 {px} {p(2)} rgb(0 0 0 / 0.15);\n"
        f"  --drop-shadow-md: 0 {p(3)} {p(3)} rgb(0 0 0 / 0.12);\n"
        f"  --drop-shadow-lg: 0 {p(4)} {p(4)} rgb(0 0 0 / 0.15);\n"
        f"  --drop-shadow-xl: 0 {p(9)} {p(7)} rgb(0 0 0 / 0.1);\n"
        f"  --drop-shadow-2xl: 0 {p(25)} {p(25)} rgb(0 0 0 / 0.15);\n"
        f"  --drop-shadow: 0 {px} {p(2)} rgb(0 0 0 / 0.1), "
        f"0 {px} {px} rgb(0 0 0 / 0.06);\n"
    )


def render_grid():
    """Pixel grid: --qs-px, derived theme lengths, border/ring/divide snaps.

    Owns --qs-px only — never --qs-zoom. The zoom default lives in base-N's
    @layer theme, and --qs-px reads it via var(--qs-zoom, 1). Disjoint ownership
    makes import order irrelevant: re-importing grid.css after a base-N cannot
    reset zoom.

    --container-* stays static rem. Deriving it breaks Tailwind v4 container-query
    variants (@md:, @min-md:) — var() is illegal inside @container conditions, and
    the compiler silently drops those utilities. Use max-w-[calc(var(--qs-px)*N)]
    for grid-exact widths.
    """
    rem = rem_size(1)
    radius_lines = "".join(
        f"  --radius-{name}: {grid_length(n)};\n" for name, n in RADIUS_STEPS
    )
    radius_lines += f"  --radius: {grid_length(4)};\n"
    tracking_lines = "".join(
        f"  --tracking-{name}: {grid_length(n)};\n" for name, n in TRACKING_STEPS
    )
    leading_lines = "".join(
        f"  --leading-{name}: 1;\n"
        for name in ("tight", "snug", "normal", "relaxed", "loose")
    )

    return (
        "/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.\n"
        " *\n"
        " * Pixel grid. --qs-px is one source pixel; every length here is an integer\n"
        " * multiple of it. --qs-zoom (set by a base-N preset, or by you) multiplies\n"
        " * the unit. This file never declares --qs-zoom — re-importing it cannot\n"
        " * reset a preset's default.\n"
        " *\n"
        " *   @import \"tailwindcss\";\n"
        " *   @import \"quanta-strike/base-12.css\";  (pulls this in)\n"
        " *\n"
        " * Or alone, for hand-rolled setups:\n"
        " *   @import \"quanta-strike/grid.css\";\n"
        " *\n"
        " * https://github.com/dithernaut/quanta-strike\n"
        " */\n"
        "\n:root {\n"
        f"  --qs-px: calc({rem} * var(--qs-zoom, 1)); "
        "/* one source pixel; follows --qs-zoom */\n"
        "}\n"
        "\n@theme {\n"
        "  /* Same as Tailwind's 0.25rem default at zoom 1. Expressed in source\n"
        "     pixels so it follows --qs-px. */\n"
        "  --spacing: calc(var(--qs-px) * 4);\n"
        "\n"
        "  /* Drive Tailwind's border utility generator so responsive, state, and\n"
        "     other variants use the same grid widths as their base utilities. */\n"
        "  --default-border-width: var(--qs-px);\n"
        + "".join(
            f"  --border-width-{w}: {grid_length(w)};\n"
            for w in BORDER_WIDTHS
        )
        + "\n"
        "  /* Integer radii — keep rounded-* doing something; 0 everywhere is\n"
        "     the more honest pixel default if you want it. */\n"
        f"{radius_lines}"
        "\n"
        "  /* Letter-spacing must be 0 or whole units — fractional em tracking\n"
        "     pushes glyph origins off the grid and blurs every glyph after the first. */\n"
        f"{tracking_lines}"
        "\n"
        "  /* Unitless leading on the grid. Presets also force line-height: 1. */\n"
        f"{leading_lines}"
        "\n"
        "  /* Shadow offsets on the grid; blur stays soft. */\n"
        f"{shadow_theme_rules()}"
        "}\n"
        "\n/* Other px-literal line utilities: stock Tailwind leaves the grid when\n"
        "   --qs-px grows. One source pixel is the thinnest honest line. N means\n"
        "   N source pixels; other numbers stay literal px. */\n"
        "@layer utilities {\n"
        + outline_grid_rules()
        + ring_grid_rules()
        + divide_grid_rules()
        + "}\n"
        "\n/* Underline and strikethrough, the same unit as the borders above. Left at\n"
        "   `auto` the engines split: Blink and Gecko read the font's own stroke,\n"
        "   WebKit derives one from font-size and lands under a source pixel.\n"
        "   --qs-rule is what a strike class publishes as its own stroke, and it\n"
        "   inherits, so a strike that draws thicker than one pixel (the 32) keeps\n"
        "   its design and everything else falls back to the grid unit. */\n"
        "@layer utilities {\n"
        "  :where(a, u, s, ins, del, abbr) {\n"
        "    text-decoration-thickness: var(--qs-rule, var(--qs-px));\n"
        "  }\n"
        "}\n"
    )


def main():
    parser = argparse.ArgumentParser(description="Generate quanta-strike CSS from a built WOFF2 tree.")
    parser.add_argument("woff2_dir", help="directory holding quanta-strike/ and quanta-strike-mono/")
    parser.add_argument("--out", help="where to write the CSS (default: the woff2 dir)")
    parser.add_argument("--url-prefix", default="", help="prepended to every font URL")
    parser.add_argument("--flat", action="store_true", help="every woff2 sits in one folder")
    parser.add_argument("--ttf-dir",
                        help="built TTFs to read underline metrics from "
                             "(default: a ttf/ folder beside the woff2 dir)")
    args = parser.parse_args()

    woff2_dir = Path(args.woff2_dir)
    if not woff2_dir.is_dir():
        print(f"error: {woff2_dir} is not a directory", file=sys.stderr)
        return 1

    strikes = find_strikes(woff2_dir)
    if not strikes:
        print(f"error: no quanta-strike woff2 files found under {woff2_dir}", file=sys.stderr)
        return 1

    out_dir = Path(args.out) if args.out else woff2_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    sizes = list(strikes)
    # WOFF2 table data is brotli-compressed, so the underline metrics have to
    # come from the TTFs the same build produced.
    load_decoration(Path(args.ttf_dir) if args.ttf_dir else woff2_dir.parent / "ttf",
                    sizes)
    mono_sizes = [s for s in sizes if "mono" in strikes[s]]
    written = []

    def write(path, text):
        path.write_text(text)
        written.append(path)

    # fonts.css — faces + vars only (the door for projects with their own scale).
    write(out_dir / "fonts.css",
          render_core(strikes, sizes, args.url_prefix, args.flat))

    # quanta-strike.css — fonts + locked classes. The bare package entry.
    write(
        out_dir / "quanta-strike.css",
        '@import "./fonts.css";\n\n'
        + HEADER
        + render_utilities(strikes, sizes),
    )

    # utilities.css — alias so old imports keep working.
    write(
        out_dir / "utilities.css",
        "/* quanta-strike — generated by scripts/generate-css.py. Do not edit by hand.\n"
        " * Alias of quanta-strike.css — prefer @import \"quanta-strike\".\n"
        " */\n"
        '@import "./quanta-strike.css";\n',
    )

    if mono_sizes:
        write(
            out_dir / "mono.css",
            render_core(strikes, mono_sizes, args.url_prefix, args.flat, mono_only=True),
        )
        write(
            out_dir / "utilities-mono.css",
            '@import "./mono.css";\n\n'
            + HEADER
            + render_utilities(strikes, mono_sizes, mono_only=True),
        )

    # Per-strike files: faces + locked classes. Publish names are N.css.
    for size in sizes:
        write(
            out_dir / f"{size}.css",
            render_core(strikes, [size], args.url_prefix, args.flat)
            + render_utilities(strikes, [size]),
        )

    for size in mono_sizes:
        write(
            out_dir / f"{size}-mono.css",
            render_core(strikes, [size], args.url_prefix, args.flat, mono_only=True)
            + render_utilities(strikes, [size], mono_only=True),
        )

    # Clear previous presets (root + scale aliases) so a removed strike disappears.
    for old in out_dir.glob("base-*.css"):
        old.unlink()
    scale_dir = out_dir / "scale"
    if scale_dir.exists():
        for old in scale_dir.glob("base-*.css"):
            old.unlink()
    scale_dir.mkdir(parents=True, exist_ok=True)

    for size in sizes:
        write(out_dir / f"base-{size}.css", render_scale(size, sizes))
        write(scale_dir / f"base-{size}.css", render_scale_alias(size))
    for size in mono_sizes:
        write(out_dir / f"base-{size}-mono.css", render_scale(size, sizes, mono=True))
        write(scale_dir / f"base-{size}-mono.css", render_scale_alias(size, mono=True))

    write(out_dir / "grid.css", render_grid())

    # Drop legacy long names left by older generator runs in this out dir.
    for legacy in (
        "quanta-strike-mono.css",
        "quanta-strike-utilities.css",
        "quanta-strike-utilities-mono.css",
    ):
        path = out_dir / legacy
        if path.exists():
            path.unlink()
    for path in out_dir.glob("quanta-strike-[0-9]*.css"):
        path.unlink()

    variants = sum(len(v) for v in strikes.values())
    print(f"Wrote {len(written)} CSS file(s) for {len(sizes)} strike(s), {variants} font file(s):")
    for path in written:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
